site_name: "BitePy - A Python Battery Intraday Trading Engine"
site_url: "https://dschaurecker.github.io/bitepy/"

site_description: "Documentation for BitePy: a Python high-frequency intraday trading engine for simulating battery strategies on the European market using dynamic programming."

nav:
  - Home: index.md
  - Data Preprocessing: data.md
  - Simulation: simulation.md
  - Results Postprocessing: results.md
  - About: about.md
  - Issues [Github] : "https://github.com/dschaurecker/bitepy/issues"
  - Source [Github] : "https://github.com/dschaurecker/bitepy/tree/main"
  - Licence [Github] : "https://github.com/dschaurecker/bitepy/blob/main/LICENSE"

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep orange
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep orange
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: "assets/bite_logo.png"
  favicon: "assets/bite_logo.png"

plugins:
  - search
  - mkdocstrings
  - exclude:
      glob:
        - "bitepy/cpp-source-submodule/*"
        - "bitepy/_bite.cpp"