site_name: "BITE Documentation"
site_url: "https://dschaurecker.github.io/bite/"

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings
  - exclude:
      glob:
        - "bite/cpp-source-submodule/*"
        - "bite/_bite.cpp"