site_name: "BITE - Battery Intraday Trading Engine"
site_url: "https://dschaurecker.github.io/bite/"

nav:
  - Home: index.md
  - Data Preprocessing: data.md
  - Simulation: simulation.md
  - Results Postprocessing: results.md
  - About: about.md
  - Issues [Github] : "https://github.com/dschaurecker/bite/issues"
  - Source [Github] : "https://github.com/dschaurecker/bite/tree/main"
  - Licence [Github] : "https://github.com/dschaurecker/bite/blob/main/LICENSE"

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep orange
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep orange
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: "assets/bite_logo.png"
  favicon: "assets/bite_logo.png"

plugins:
  - search
  - mkdocstrings
  - exclude:
      glob:
        - "bite/cpp-source-submodule/*"
        - "bite/_bite.cpp"